apiVersion: v1
kind: Service
metadata: 
  name: ratings
  namespace: {{ .Values.namespace }}

spec: 
  selector: 
    app.kubernetes.io/component: ratings
  
  ports:
    - name: http
      port: {{ .Values.ratings.service.port }} 
      targetPort: {{ .Values.ratings.service.port }}
