apiVersion: v1
kind: Secret 
metadata:
  name: {{ .Values.payment.gateway.secretName }}
  namespace: {{ .Values.namespace }}

type: Opaque
stringData:
  api-key: {{ .Values.payment.gateway.apiKey | quote }}