{{- if .Values.payment.serviceAccount.create }}

apiVersion: v1
kind: ServiceAccount 
metadata:
  name: {{ .Values.payment.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels: 
    app.kubernetes.io/name: robot-shop
    app.kubernetes.io/managed-by: helm 
    app.kubernetes.io/component: serviceaccount-payment
    

automountServiceAccountToken: false
imagePullSecrets: 
  - name: {{ .Values.payment.serviceAccount.imagePullSecret }}

{{- end }}