{{- if .Values.ingressLocal.tls.enabled }}

apiVersion: v1
kind: Secret

metadata:
  name: {{ .Values.ingressLocal.tls.secretName }}
  namespace: {{ .Values.namespace }}

type: kubernetes.io/tls

data:
  tls.crt: {{ .Values.ingressLocal.tls.crt }}
  tls.key: {{ .Values.ingressLocal.tls.key }}

{{- end }}