apiVersion: v1
kind: Service 
metadata:
  name: cart
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: cart
  ports:
    - name: http
      port: {{ .Values.cart.service.port }}
      targetPort: {{ .Values.cart.service.port }}