{{- if .Values.limitRange.enabled}}

apiVersion: v1
kind: LimitRange

metadata:
  name: robot-shop-limits
  namespace: {{ .Values.namespace }}

spec:
  limits:

    - type: Container

      default:
        cpu: {{ .Values.limitRange.container.defaults.cpu | quote }}
        memory: {{ .Values.limitRange.container.defaults.memory | quote }}

      defaultRequest:
        cpu: {{ .Values.limitRange.container.defaultRequest.cpu | quote }}
        memory: {{ .Values.limitRange.container.defaultRequest.memory | quote }}

      max:
        cpu: {{ .Values.limitRange.container.max.cpu | quote }}
        memory: {{ .Values.limitRange.container.max.memory | quote }}

      min:
        cpu: {{ .Values.limitRange.container.min.cpu | quote }}
        memory: {{ .Values.limitRange.container.min.memory | quote }}

    - type: PersistentVolumeClaim

      max:
        storage: {{ .Values.limitRange.pvc.maxStorage | quote }}

      min:
        storage: {{ .Values.limitRange.pvc.minStorage | quote }}

{{- end }}