apiVersion: v1
kind: Service
metadata: 
  name: rabbitmq
  namespace: robot-shop
  labels:
    app.kubernetes.io/name: robot-shop
    app.kubernetes.io/component: rabbitmq

spec: 
  clusterIP: None
  selector: 
    app.kubernetes.io/component: rabbitmq
  ports:
  - name: amqp
    port:  {{ .Values.rabbitmq.service.amqpPort }}
    targetPort: {{ .Values.rabbitmq.service.amqpPort }}

  - name: management
    port: {{ .Values.rabbitmq.service.managementPort }}
    targetPort: {{ .Values.rabbitmq.service.managementPort }}