apiVersion: v1
kind: Secret

metadata: 
  name: {{ .Values.rabbitmq.auth.secretName }}
  namespace: {{ .Values.namespace }}

type: Opaque

stringData:
  username: {{ .Values.rabbitmq.auth.username | quote }}
  password: {{ .Values.rabbitmq.auth.password | quote }}
