#_______ Erlang Cookie Secret

apiVersion: v1
kind: Secret
metadata: 
  name: {{ .Values.rabbitmq.erlangCookie.secretName }}

  namespace: {{ .Values.namespace }}
  labels: 
    app.kubernetes.io/name: robot-shop
    app.kubernetes.io/component: rabbitmq
type: Opaque
stringData:
  cookie: {{ .Values.rabbitmq.erlangCookie.cookie | quote }}